name: exiv2
version: 0.1.0
description: Dart VM native extension wrapper for exiv2 library for manipulating EXIF metadata
homepage: https://github.com/martinsik/dart-exiv2-ext
author: Martin Sikora
dependencies:
  test: "^0.12.0"
dev_dependencies:
  xml: "^2.3.2"
  simple_requests: "^0.1.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
